### ISSUE TITLE
Errors: Must provide an operation.

### ISSUE THREAD

**Issue by michaelinglis** [dadish/ProcessGraphQL#1]
Getting:

```json
{"errors":[{"message":"Must provide an operation."}]}
````
when following all instructions to access qraphql on a page. The query is:
```graphql
{
    home {
        list {
            title
        }
    }
}
```
Running pw version 3.0.42, most recent ProcessGraphQL, on fresh "Classic" profile.

**Comment by dadish** [comment]
That message says that the module is working but did receive empty `query` variable, or didn't receive it at all. Are you making this request via GraphiQL interface? The GraphiQL interface should be located at __Setup__ -> __GraphQL__ in your admin panel.

If you are making request from your own script, like jQuery, you should send a __query__ parameter with a string in it. Should look something like this.
```js
$.post(
  '/processwire/setup/graphql/', // change this line if you changed admin path, like '/admin/setup/graphql/'
  {
    query: "{ home {list { title } } }"
  },
  function (res) {
    console.log(res);
  }
);
```

**Comment by michaelinglis** [comment]
Thank you for the module and taking the time to help! 

I think I am just confused and perhaps have the wrong expectations.

With a template **graphql** containing:
```php
$ProcessGraphQL = $modules->get('ProcessGraphQL');
echo $ProcessGraphQL->executeGraphQL();
```
and a page /graphql I get the error mentioned above.

Initially I was expecting this to echo the query defined in the GraphiQL interface.

Your example JQuery post works fine, but changing to the public url I have defined returns the same error.
```javascript
$.post(
  '/graphql/',
  {
    query: "{ home {list { title } } }"
  },
  function (res) {
    console.log(res);
  }
);
```

Thanks again.

**Comment by dadish** [comment]
I think I might know what it is. If you are requesting to `/graphql` instead of `/graphql/` (_notice the slash in the end_) then you will get this error. Because ProcessWire redirects urls that do not end with `/` to the same urls with the `/`. Take a look at your network requests in browser developer tools. Here is what might be happening.

First request sends the query. But it won't reach your template file, ProcessWire returns 301.

<img width="749" alt="with_query" src="https://cloud.githubusercontent.com/assets/2578542/22624147/9c25dc32-eb9c-11e6-8c33-1664f27cadfc.png">

Second request reaches your template, but there is no query in it.

<img width="750" alt="without_query" src="https://cloud.githubusercontent.com/assets/2578542/22624148/9ea37f1e-eb9c-11e6-9eb0-a02bf857ddc3.png">

Is this your case?

**Comment by michaelinglis** [comment]
Right you are, I thought I double checked that testing earlier. Thanks for your help! Looking forward to exploring more now.
