### ISSUE TITLE
datetime is not parsed correctly

### ISSUE THREAD

**Issue by lesaff** [dadish/ProcessGraphQL#15]
I have a `publish_from` field that is storing datetime data. It's recognized as datetime in the GraphicQL interface but when parsed via Ajax, it's returning either `null` or `12-31-1969`

I am testing the latest GraphQL btw.

Thx

**Comment by dadish** [comment]
@lesaff Made some updates to `FieldtypeDatetime` field. Please see if your issue is fixed and let me know.

Also, now you can pass a `format` argument that is a [PHP date](https://secure.php.net/manual/en/function.date.php) formatting string and you will get your dates formatted exactly how you want.

**Comment by lesaff** [comment]
That did it. Thx! 🌮
