### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by martinkirk** [dadish/ProcessGraphQL#2]
I've installed the GraphQL module in PW but I'm getting an 'Internal Server Error' when I try to access the interactive query tool.  In the GraphQL results pane I see the following:

Error: Internal Server Error
    at c.<anonymous> (/site/modules/ProcessGraphQL/GraphiQL/build/static/js/main.a8a92523.js:20:31302)
    at c.r.emit (/site/modules/ProcessGraphQL/GraphiQL/build/static/js/main.a8a92523.js:14:19334)
    at XMLHttpRequest.t.onreadystatechange (/site/modules/ProcessGraphQL/GraphiQL/build/static/js/main.a8a92523.js:21:3815)

In the Processwire error log I get:

Error: Class 'Youshido\GraphQL\Type\Scalar\DatetimeType' not found (line 12 of /site/modules/ProcessGraphQL/src/Field/Page/Fieldtype/FieldtypeDatetime.php)

My PHP version is 5.4.41 and my PW version is 3.0.42

**Comment by martinkirk** [comment]
Ok, I've fixed it.  Here's what I had to do...

in /site/modules/ProcessGraphQL/src/Field/Page/Fieldtype/FieldtypeDatetime.php

I changed
use Youshido\GraphQL\Type\Scalar\DatetimeType;
to
use Youshido\GraphQL\Type\Scalar\DateTimeType;

then I got a different error:

Parse Error: syntax error, unexpected '[' (line 109 of /site/modules/ProcessGraphQL/vendor/youshido/graphql/src/Parser/Token.php)

to fix that one I removed what looked like a spurious '[$tokenType]'  which immediately followed the closing ']' of the return value.

it now looks to be working ok, both interactive & remote.

(please let me know if I've done something I shouldn't have!)

**Comment by dadish** [comment]
Hey. I had hard time trying to reproduce the first bug you had. Now I get it, because I work on Mac OS machine and it is not case-sensitive with the filenames. I will fix that one.

The second error you got is probably because of the PHP version of yours. I know the module says that you need PHP >= 5.4, but it turns out the [GraphQL library](https://github.com/Youshido/GraphQL) I use for this module requires PHP >= 5.5. Now that's a bummer. I suppose I will have to update the documentation on that one.

Thanks for bringing up this issue.

**Comment by dadish** [comment]
@martinkirk . I pushed the fix for the first bug you got.

As I mentioned the second bug is related to the third-party library I use. Please upgrade your PHP to 5.5.x. As this module from now will require PHP version >= 5.5. Sorry for inconvenience, but there isn't much I can do, because it is required by the GraphQL library I use for this module.

BTW the code you removed from `Token.php` file you mentioned, the `[$tokenType]`. It is supposed to be there. That's the GraphQL library code. You should not modify it, because it probably will cause you issues in the future even if everything works fine for now.

**Comment by martinkirk** [comment]
Hi @dadish 

You're correct, on second glance the bit I removed was required (I haven't encountered any errors yet but I'm sure I would).
I'll upgrade my PHP version when I get a chance but, as a quick-fix, I've modified the 'tokenName'  function in /site/modules/ProcessGraphQL/vendor/youshido/graphql/src/Parser/Token.php
to use the older PHP syntax while still functioning as it's supposed to.
